"""add markdown field

Revision ID: 287ceeba6e12
Revises: 9d9b69094de1
Create Date: 2026-01-08 12:18:59.274367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287ceeba6e12'
down_revision: Union[str, Sequence[str], None] = '9d9b69094de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anthropic_articles', sa.Column('markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anthropic_articles', 'markdown')
    # ### end Alembic commands ###
